#!/usr/bin/env bash
# Tool Name :- Sky-IP-Tracer
# Author :- Egehan Gökden
# Date :- 27/3/2022

case "$1" in
  -m)
    php modules/.tracem.php
  ;;
  -t)
    case "$#" in
    2)
      php modules/.traceip.php $2
    ;;
    *)
      echo "hata : geçersiz argümanlar!!"
      echo "Kullanımı: trace -t <hedef_ip>"
    ;;
    esac
  ;;
  -u)
    php modules/.update.php
    exit
  ;;
  update)
    php modules/.update.php
    exit
  ;;
  start)
    php .Sky-IP-Tracer.php
    exit
  ;;
  -rm)
    php modules/.uninstall.php
    exit
  ;;
  *)
    echo "Kullanım: trace [Komutlar]... [Argümanlar]..."
    echo " Komutlar:"
    echo " -t <hedef_ip>       Hedef ip'yi bulur."
    echo " -m                  sizin ipnizi gösterir."
    echo " -h                  Yardım menüsünü açar."
    echo " -u                  Sky-IP-Tracer'ı güncellemek için."
    echo " help                Yardım menüsünü açar."
    echo " update              to update ip-tracer."
    echo " start               Sky-İP-Tracer menüsünü açar."
esac
